/// Flutter icons CurrencyIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CurrencyIcons
///      fonts:
///       - asset: fonts/CurrencyIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CurrencyIcons {
  CurrencyIcons._();

  static const _kFontFam = 'CurrencyIcons';
  static const String? _kFontPkg = null;

  static const IconData pokeball =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zelda =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData animalCrossing =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
